/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e16c5efc-71d3-4535-b3ec-364b41aebdee",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_f57Tfleb6",
    "aws_user_pools_web_client_id": "7sjppk9b4adt87insn0o9o9uie",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "6",
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://vjkakaf55fbytfpjyx4ha4m65m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fmcy3kmggrftjafnleoz2rgr24",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://d3w6n5srj8.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "bookingsRestApi",
            "endpoint": "https://vrvy2yikk6.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "paymentsApi",
            "endpoint": "https://bkyj8lov9g.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "bookingsTable-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
